# Generated by Django 3.0.7 on 2020-06-29 07:48

from django.db import migrations, models
import trip_project.trip_app.model_managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_sqn', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='firstname', max_length=50)),
                ('last_name', models.CharField(db_column='lastname', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(db_column='mobile', max_length=20)),
                ('last_login', models.DateTimeField(auto_now_add=True, db_column='last_login')),
                ('is_active', models.BooleanField(db_column='isActive', default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', trip_project.trip_app.model_managers.UserManager()),
            ],
        ),
    ]
