# Generated by Django 3.0.7 on 2020-07-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0003_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='TripImages',
            fields=[
                ('images_sqn', models.BigAutoField(primary_key=True, serialize=False)),
                ('images', models.FileField(blank=True, null=True, upload_to='')),
                ('trip', models.ForeignKey(db_column='trip_sqn', on_delete=django.db.models.deletion.PROTECT, to='trip_app.Trips')),
            ],
        ),
    ]
