# Generated by Django 3.0.7 on 2020-07-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0004_auto_20200704_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='at_location', null=True),
        ),
        migrations.AlterField(
            model_name='tripimages',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='memories'),
        ),
    ]
